manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: devpew
      url-base: https://github.com/devpew
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 118359c8
      import: app/west.yml
    - name: charybdis-3-6-dongle-prospector-studio
      remote: devpew
      revision: 6583513f24162b523113fca96c089e22aa87d748
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: a1a0f35ab6750c8fc72b84ea00add1e5fbaea1e4
  self:
    path: config