manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: alexrorsh
      url-base: https://github.com/alexrorsh
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 4ec69cb
      import: app/west.yml
    - name: charybdis-3-6-dongle-prospector-studio
      remote: alexrorsh
      revision: fa48c4d248f6c88c84e7b62bdf076af5ceeafb34
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: 77635ba
  self:
    path: config