manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: alexrorsh
      url-base: https://github.com/alexrorsh
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 118359c8
      import: app/west.yml
    - name: charybdis-3-6-dongle-prospector-studio
      remote: alexrorsh
      revision: fa48c4d248f6c88c84e7b62bdf076af5ceeafb34
  self:
    path: config